"""Schema initial FoodSave

Revision ID: 18c0274dc0a6
Revises: 
Create Date: 2026-09-29 14:10:34.680530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18c0274dc0a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produit_ontologie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=120), nullable=False),
    sa.Column('nom_normalise', sa.String(length=120), nullable=False),
    sa.Column('classe', sa.String(length=50), nullable=False),
    sa.Column('conservation_jours', sa.Integer(), nullable=True),
    sa.Column('transformations', sa.Text(), nullable=True),
    sa.Column('compatibles', sa.Text(), nullable=True),
    sa.Column('astuce', sa.Text(), nullable=True),
    sa.Column('saison', sa.String(length=30), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('nb_utilisations', sa.Integer(), nullable=True),
    sa.Column('raison_rejet', sa.String(length=300), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('date_modification', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('produit_ontologie', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_produit_ontologie_nom_normalise'), ['nom_normalise'], unique=False)
        batch_op.create_index(batch_op.f('ix_produit_ontologie_statut'), ['statut'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('ville', sa.String(length=80), nullable=False),
    sa.Column('region', sa.String(length=80), nullable=True),
    sa.Column('pays', sa.String(length=20), nullable=False),
    sa.Column('telephone', sa.String(length=30), nullable=True),
    sa.Column('est_suspendu', sa.Boolean(), nullable=False),
    sa.Column('motif_suspension', sa.String(length=300), nullable=True),
    sa.Column('date_suspension', sa.DateTime(), nullable=True),
    sa.Column('date_inscription', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('annonce',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('produit', sa.String(length=150), nullable=False),
    sa.Column('produit_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('categorie', sa.String(length=50), nullable=False),
    sa.Column('etat_produit', sa.String(length=20), nullable=False),
    sa.Column('quantite', sa.Float(), nullable=False),
    sa.Column('unite', sa.String(length=20), nullable=True),
    sa.Column('prix', sa.Float(), nullable=True),
    sa.Column('type_offre', sa.String(length=10), nullable=True),
    sa.Column('date_peremption', sa.Date(), nullable=False),
    sa.Column('photo_filename', sa.String(length=300), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('urgence', sa.String(length=20), nullable=True),
    sa.Column('ville', sa.String(length=80), nullable=False),
    sa.Column('region', sa.String(length=80), nullable=True),
    sa.Column('pays', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['produit_id'], ['produit_ontologie.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log_action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('type_action', sa.String(length=50), nullable=False),
    sa.Column('cible_id', sa.Integer(), nullable=True),
    sa.Column('cible_type', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('date_action', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('annonce_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['annonce_id'], ['annonce.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservation')
    op.drop_table('log_action')
    op.drop_table('annonce')
    op.drop_table('user')
    with op.batch_alter_table('produit_ontologie', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_produit_ontologie_statut'))
        batch_op.drop_index(batch_op.f('ix_produit_ontologie_nom_normalise'))

    op.drop_table('produit_ontologie')
    # ### end Alembic commands ###
