"""Ajout securite bcrypt + RGPD + anti brute-force

Revision ID: 911bf4ffbd67
Revises: 9cb290c362f0
Create Date: 2026-09-29 16:45:04.010392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '911bf4ffbd67'
down_revision = '9cb290c362f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # Colonnes NOT NULL : on donne une valeur par defaut aux lignes existantes.
        batch_op.add_column(sa.Column('consentement_rgpd', sa.Boolean(),
                                      nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('date_consentement', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('effacement_demande', sa.Boolean(),
                                      nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('date_effacement', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('tentatives_echouees', sa.Integer(),
                                      nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('bloque_jusqua', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('derniere_connexion', sa.DateTime(), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=128),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=False)
    # ### end Alembic commands ###

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)
        batch_op.drop_column('derniere_connexion')
        batch_op.drop_column('bloque_jusqua')
        batch_op.drop_column('tentatives_echouees')
        batch_op.drop_column('date_effacement')
        batch_op.drop_column('effacement_demande')
        batch_op.drop_column('date_consentement')
        batch_op.drop_column('consentement_rgpd')

    # ### end Alembic commands ###
