"""Ajout table message pour la messagerie interne

Revision ID: 9cb290c362f0
Revises: 18c0274dc0a6
Create Date: 2026-09-29 16:18:56.682069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cb290c362f0'
down_revision = '18c0274dc0a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expediteur_id', sa.Integer(), nullable=False),
    sa.Column('destinataire_id', sa.Integer(), nullable=False),
    sa.Column('annonce_id', sa.Integer(), nullable=True),
    sa.Column('sujet', sa.String(length=200), nullable=True),
    sa.Column('contenu', sa.Text(), nullable=False),
    sa.Column('lu', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('lu_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['annonce_id'], ['annonce.id'], ),
    sa.ForeignKeyConstraint(['destinataire_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['expediteur_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_destinataire_id'), ['destinataire_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_expediteur_id'), ['expediteur_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_expediteur_id'))
        batch_op.drop_index(batch_op.f('ix_message_destinataire_id'))
        batch_op.drop_index(batch_op.f('ix_message_created_at'))

    op.drop_table('message')
    # ### end Alembic commands ###
